异常与异常捕获
----------------------

有时候，我们不希望程序异常退出，而是希望捕获异常并让函数正常执行，这涉及 defer 和 recover 的结合使用。



### panic 函数使用方法

Go 语言中的 panic 方法并不会导致程序异常退出，而是会终止当前函数的正常执行，并执行 defer 函数并逐级返回。除了手动触发 panic，在 Go 语言运行时的一些阶段也会检查并触发 panic，例如数组越界及 map 并发冲突。



### 异常捕获与 recover

为了让程序在 panic 时仍然能够执行后续的流程，Go 语言提供了内置的 recover 函数用于异常恢复。recover 函数一般与 defer 函数结合使用才有意义，其返回值是 panic 中传递的参数。



### panic 与 recover 的嵌套

重复嵌套的 panic 并不会陷入死循环，每一次的 panic 调用实际都会新建一个 _panic 结构体，并用一个链表进行存储。

```go
```

同时，recover 函数最终捕获的是最近发生的 panic（链表头部），即使有多个 panic 函数，在最上层的函数也只需要一个 recover 函数就能让函数按照正常的流程执行。

```go
```

